<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Jwt.Refresh.Token.Cosmos</PackageId>
        <Authors>Bs3</Authors>
        <PackageTags>jwt refresh-token authentication cosmosdb azure dotnet</PackageTags>
        <Title>JWT Refresh Token with Cosmos DB</Title>
        <Description>Library for managing JWT access tokens and refresh tokens using Azure Cosmos DB</Description>
        <Copyright>bs3.dev</Copyright>
        <RepositoryUrl>https://github.com/bs3dev/jwt-refresh-token</RepositoryUrl>
        <Version>4.0.0-preview</Version>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageProjectUrl>https://github.com/bs3dev/jwt-refresh-token</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Domain\Jwt.Refresh.Token.Domain\Jwt.Refresh.Token.Domain.csproj" />
      <ProjectReference Include="..\Jwt.Refresh.Token.Infra\Jwt.Refresh.Token.Infra.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.48.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.4" />
    </ItemGroup>

    <PropertyGroup>
        <AzureCosmosDisableNewtonsoftJsonCheck>true</AzureCosmosDisableNewtonsoftJsonCheck>
    </PropertyGroup>


</Project>
