<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>$(PackageVersion)</Version>
        <Description>Infra | Library for managing JWT access tokens and refresh tokens using Azure Cosmos DB</Description>
        <Copyright>bs3.dev</Copyright>
        <Title>Infra | JWT Refresh Token with Cosmos DB</Title>
        <Authors>Bs3</Authors>
        <PackageProjectUrl>https://github.com/bs3dev/jwt-refresh-token</PackageProjectUrl>
        <RepositoryUrl>https://github.com/bs3dev/jwt-refresh-token</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Application\Jwt.Refresh.Token.Application\Jwt.Refresh.Token.Application.csproj" />
      <ProjectReference Include="..\..\Domain\Jwt.Refresh.Token.Domain\Jwt.Refresh.Token.Domain.csproj" />
    </ItemGroup>

</Project>
