<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
         <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Description>Application | Library for managing JWT access tokens and refresh tokens using Azure Cosmos DB</Description>
        <Version>$(PackageVersion)</Version>
        <Title>Application | JWT Refresh Token with Cosmos DB</Title>
        <Authors>Bs3</Authors>
        <Copyright>bs3.dev</Copyright>
        <PackageProjectUrl>https://github.com/bs3dev/jwt-refresh-token</PackageProjectUrl>
        <RepositoryUrl>https://github.com/bs3dev/jwt-refresh-token</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Domain\Jwt.Refresh.Token.Domain\Jwt.Refresh.Token.Domain.csproj" />
    </ItemGroup>

</Project>
